### ISSUE TITLE
flume package missing symbolic link

### ISSUE THREAD

**Issue by jucaf** [keedio/buildoop#51] opened 2014-03-24 12:25 UTC
Symbolync link 
/usr/lib/flume/lib/hadoop-auth.jar --> /usr/lib/hadoop/hadoop-auth.jar should point to  /usr/lib/hadoop/hadoop-auth-2.2.0.jar 
usr/lib/flume/lib/hadoop-common.jar-->/usr/lib/hadoop/hadoop-common.jar to usr/lib/hadoop/hadoop-common-2.2.0.jar

**Comment by javiroman** [comment] 2014-03-24 12:36
Duplicate of #42

**Closed as completed by javiroman** 2014-03-24 12:36 UTC
Labels: duplicate
